name: Pinpit CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Install Wine
      run: sudo dpkg --add-architecture i386 &&
           sudo mkdir -pm755 /etc/apt/keyrings &&
           sudo wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key &&
           sudo wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/kinetic/winehq-kinetic.sources &&
           sudo apt update &&
           sudo apt install winehq-stable
    - name: Install Wine Mono
      run: wget https://dl.winehq.org/wine/wine-mono/8.0.0/wine-mono-8.0.0-x86.msi &&
           wine msiexec /i wine-mono-8.0.0-x86.msi
    - name: Setup project
      run: ./gradlew createRuntime
    - name: Create C4D project and package
      run: >
        ./scripts/pinpit create-project-compose-for-desktop \
          --output test-c4d --project-name "Foo Tool" --package "com.foo.tool" \
          --description "a tool for doing fancy stuff" \
          --vendor-full "Bar Inc" --vendor-short "Bar" \
          --input src/test/resources/rocket.svg &&
          cd test-c4d && ./gradlew pinpitPackageDefault
